name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate Conventional Commits PR
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: catalystsquad/action-validate-conventional-commits-pr@v1
  test:
    if: github.event.pull_request.draft == false
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          # In order:
          # * go Module download cache
          # * go Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Compile
        run: |
          git config --global url."https://${{ secrets.AUTOMATION_PAT }}@github.com".insteadOf "https://github.com"
          go build ./...
          go test
